service: dev-graphql-subscription

provider:
  name: aws
  runtime: go1.x
  region: ap-southeast-2
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'lambda:*'
            - 'dynamodb:*'
          Resource: '*'

package:
  exclude:
    - ./**
  include:
    - ./dist/**

functions:
  ws-connect:
    handler: dist/api
    name: graphql-subscription-ws
    timeout: 30
    tracing: true
    environment:
      HANDLER_NAME: graphql
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default
  dbstream:
    handler: dist/api
    name: dbstream
    timeout: 30
    tracing: true
    environment:
      HANDLER_NAME: stream
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [ConnectionTable, StreamArn]
            # filterPatterns:
            #   - eventName: [MODIFY, INSERT]
            # dynamodb:
            #   NewImage:
            #     type:
            #       S:
            #         - prefix: event.

resources:
  Resources:
    ConnectionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Connection
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: type
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: type
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
