service: dev-graphql-subscription

provider:
  name: aws
  runtime: go1.x
  region: ap-southeast-2
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'lambda:*'
          Resource: '*'

package:
  exclude:
    - ./**
  include:
    - ./dist/**

functions:
  # api:
  #   handler: dist/api
  #   name: graphql-subscription-api-handler
  #   timeout: 30
  #   tracing: true
  #   environment:
  #     HANDLER_NAME: api
  #   events:
  #     - http:
  #         path: /query
  #         method: post

  ws-connect:
    handler: dist/api
    name: graphql-subscription-ws
    timeout: 30
    tracing: true
    environment:
      HANDLER_NAME: connect
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default

  # ws-default:
  #   handler: dist/api
  #   name: graphql-subscription-ws-default
  #   timeout: 30
  #   tracing: true
  #   environment:
  #     HANDLER_NAME: default
  #   events:
  #     - websocket: $default
