service: dev-graphql-subscription

provider:
  name: aws
  runtime: go1.x
  region: ap-southeast-2
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'lambda:*'
            - 'dynamodb:*'
            - execute-api:Invoke
          Resource: '*'

package:
  exclude:
    - ./**
  include:
    - ./dist/**

functions:
  graphql:
    handler: dist/api
    name: graphql-query-mutation
    timeout: 30
    tracing: true
    environment:
      HANDLER_NAME: querymutation
    events:
      - http:
          path: /graphql
          method: post
          

  ws-connect:
    handler: dist/api
    name: graphql-subscription-ws
    timeout: 30
    tracing: true
    environment:
      HANDLER_NAME: subscription
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default
  dbstream:
    handler: dist/api
    name: graphql-subscription-dbstream
    timeout: 30
    tracing: true
    environment:
      HANDLER_NAME: stream
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [ConnectionTable, StreamArn]
          filterPatterns:
            - eventName: [MODIFY, INSERT]
              dynamodb:
                NewImage:
                  type:
                    S:
                      - prefix: event.

resources:
  Resources:
    ConnectionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Connection
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: type
            AttributeType: S
          - AttributeName: topic
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: type
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

        GlobalSecondaryIndexes:
          - IndexName: topicGsi
            KeySchema:
              - AttributeName: topic
                KeyType: HASH
              - AttributeName: type
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

          - IndexName: typeGsi
            KeySchema:
              - AttributeName: type
                KeyType: HASH
              - AttributeName: id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL