service: dev-graphql-subscription

provider:
  name: aws
  runtime: go1.x
  region: ap-southeast-2
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'lambda:*'
            - 'dynamodb:*'
          Resource: '*'

package:
  exclude:
    - ./**
  include:
    - ./dist/**

functions:
  ws-connect:
    handler: dist/api
    name: graphql-subscription-ws
    timeout: 30
    tracing: true
    environment:
      HANDLER_NAME: connect
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default

resources:
  Resources:
    ConnectionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Connection
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: type
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: type
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        